# .github/workflows/release.yaml

on:
    release:
       types: [created]
permissions:
    contents: write
    packages: write
jobs:
    releases-matrix:
        name: Release Swiftwave Binary
        runs-on: ubuntu-latest
        strategy:
        matrix:
            goos: [linux]
            goarch: ["386", amd64, arm64]
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Build and publish
          uses: wangyoucao577/go-release-action@v1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            goos: ${{ matrix.goos }}
            goarch: ${{ matrix.goarch }}
            goversion: "https://dl.google.com/go/go1.22.1.linux-amd64.tar.gz"
            project_path: "."
            binary_name: "swiftwave_stats_ninja"